site_name: HyperExchange Documentation
theme: 
  name: material
  custom_dir: theme_override
  favicon: 'img/hx-icons/hx-logo.ico'
  logo: 'img/hx-icons/hx-logo.svg'
  font: false
extra:
  social:
    - type: 'github'
      link: 'https://github.com/HcashOrg/HyperExchange'
    - type: 'twitter'
      link: ''
    - type: 'reddit'
      link: ''
    - type: 'youtube'
      link: ''
site_url: https://docs.hx.org
repo_url: https://github.com/HcashOrg/Hx-Doc
repo_name: HcashOrg/Hx-Doc
markdown_extensions:
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: True
  - markdown.extensions.tables
  - pymdownx.details
  - pymdownx.arithmatex
  - fontawesome_markdown
extra_javascript:
  - js/MathJax-2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/fonts.css
  - css/style.css
pages:
- 'Home': 'index.md'
- Getting Started:
  - "Beginner's Guide": 'getting-started/beginner-guide.md'
  - 'HyperExchange Features': 'getting-started/hx-features.md'
  - 'HX Distribute': 'getting-started/obtaining-hx-test.md'
  - 'Using the Block Explorer': 'getting-started/using-the-block-explorer.md'
  - 'Using Testnet':
    - 'Using Public Testnet': 'getting-started/public-testnet.md'
    - 'Using Private Testnet': 'getting-started/private-testnet.md' 
- Wallets:
  - HyperExchange Indicator:
    - 'HXIndicator Setup': 'wallets/hxindicator-setup.md'
    - 'Using HXIndicator':
      - 'Account': 'wallets/hxindicator-using-account.md'
      - 'Contract': 'wallets/hxindicator-using-contract.md'
      - 'Advance': 'wallets/hxindicator-using-advance.md'
      - 'Contacts': 'wallets/hxindicator-using-contacts.md'
      - 'Senator': 'wallets/hxindicator-using-senator.md'
      - 'Citizen': 'wallets/hxindicator-using-citizen.md'
  - 'Building': 'wallets/hx-building.md'
  - 'docker deploy': 'wallets/hx-docker-deploy.md'
  - HyperExchange Node:
    - 'startup': 'wallets/hxnode-setup.md'
    - 'Using hx-node': 'wallets/hxnode-using.md'
  - HyperExchange Cli-wallet:
    - 'Hx-cli Startup': 'wallets/hxwallet-cli.md'
    - 'Hx-cli Commands': 'wallets/hxwallet-cli-rpc-commands.md'
  - HyperExchange Middleware:
    - 'Startup': 'wallets/middleware-startup.md'
- Advanced:
  - Cross Chain:
    - Cross-chain Technology Implementation:
      - 'Blockchain Multi Tunnel (BMT) Protocol': 'advanced/cross-chain/bmp-protocol.md'
      - 'HyperExchange Axis': 'advanced/cross-chain/hx-axis.md'
      - 'Indicator': 'advanced/cross-chain/indicator.md'
    - Cross-chain Process Flowchart:
      - 'Initialisation Process': 'advanced/cross-chain/init-process.md'
      - 'Account Creation': 'advanced/cross-chain/account-creation.md'
      - 'Cross-chain Deposit Process': 'advanced/cross-chain/cross-chain-deposit.md'
      - 'Cross-chain Withdrawal Process': 'advanced/cross-chain/cross-chain-withdrawall.md'
    - Sidechain Asset Security:
      - 'Financial Balance Strategy': 'advanced/cross-chain/financial-balance.md'
      - 'Dynamic Fund Rebalancing': 'advanced/cross-chain/fund-rebalance.md'
  - Smart Contract:
    - 'About Smart Contract': 'advanced/smart-contract/about-smart-contract.md'
    - 'Pending purchase order functionality rules': 'advanced/smart-contract/purchase-rule.md'
    - 'Smart Contract Template': 'advanced/smart-contract/smart-contract-template.md'
    - 'Fee structure': 'advanced/smart-contract/smart-contract-fee.md'
    - 'Types of Fees': 'advanced/smart-contract/smart-contract-feetype.md'      
  - Random Pool Proof of Multi- properties:
    - "Network Roles": 'advanced/pov/network-role.md'
    - "Asset Collateral": 'advanced/pov/asset-collateral.md'
    - "Consensus Protocol/Algorithm": 'advanced/pov/consensus-protocol.md'
    - "Security Features of a RPPOM Consensus Mechanism": 'advanced/pov/POV.md'
  - Community Governance:
    - 'Overview': 'advanced/community-governance/community-overview.md'
    - 'Selecting a Senator': 'advanced/community-governance/select-senator.md'
    - 'Senator Rights and Duties': 'advanced/community-governance/senator-right.md'
    - 'Citizens Involvement in the Replacement of Senators': 'advanced/community-governance/senator-replace-rule.md'
    - 'Advantages of Community Governance': 'advanced/community-governance/community-advantages.md'
- Research:
  - Smart Contract IDE:
    - 'IDE Introduce': 'research/ide/ide-introduce.md'
    - IDE Usage: 
      - 'Init & Settings': 'research/ide/ide-using.md'
      - 'Contract Edit': 'research/ide/ide-edit.md'
      - 'Contract Compile': 'research/ide/ide-compile.md'
      - 'Contract Debug': 'research/ide/ide-debug.md'
      - 'Contract Test & Deploy': 'research/ide/ide-online.md'
- FAQ:
  - 'Hx-indicator usage Questions': 'faq/wallet-usage/wallet-usage.md'
  - 'Orientation Questions':
    - 'The re-pledging of assets Model': 'faq/re-pledging-of-asset-model.md'
    - 'Smart Contracts and Virtual Machines': 'faq/contract-virtual-machine.md'
    - 'Concurrency Model': 'faq/concurrency-model.md'
    - 'Consensus-based, Random Number Generator': 'faq/consensus.md'
    - 'Events and Rollbacks': 'faq/event-rollback.md'
    - 'Local Query Interface': 'faq/local-query.md'
    - 'Asset Block Import Model': 'faq/asset-block-import-model.md'
copyright: If you wish to improve this site, please <a href="https://github.com/HcashOrg/HyperExchange/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/HcashOrg/Hx-Doc"><i class="fa fa-github"></i> send a pull request</a>.<br>hxdocs v0.0.1. HyperExchange Project 2018.
